### ISSUE TITLE
support asciidoc

### ISSUE THREAD

**Issue by nagim** [gubler/gitbook-plugin-callouts#1]
Hi,

The plugin is awesome, however, the syntax you're enforcing (`<blockquote> <h4>`...) only works in markdown.
In asciidoc, headers are not parsed in the blockquote element (at least not in GitBook), instead I got this as an output:

``` html
<div class="quoteblock">
<blockquote>
<div class="paragraph">
<p>==== Note::Note</p>
</div>
</blockquote>
</div>
```

Could you please somehow make this compatible with asciidoc?

Thanks,
Imre

**Comment by gubler** [comment]
OK, just pushed 0.0.7 which should resolve this.

**Comment by nagim** [comment]
Thanks a ton, could you also publish it as a new release? I'm using the web service and not the command line.
:bow: :beers:

**Comment by gubler** [comment]
Sorry about that (still new at this :smile: ) - published now.

**Comment by nagim** [comment]
Thanks a lot again! No worries, you're doing just fine :smile:

**Comment by nagim** [comment]
Checked and works fine! Awesome!
