### ISSUE TITLE
hide type in panel title

### ISSUE THREAD

**Issue by nagim** [gubler/gitbook-plugin-callouts#2]
Hi,

I think this could be further improved by hiding the callout type from the panel title.
For example, if I write the syntax like this:

``` asciidoc
> ==== type::title
> 
> content
```

then it generates as `Type: Title` in the panel header.
I think `Title` would be enough, since we have a header and body field as well anyway, so every description can go to the panel body, and the header should only contain the icon and the `Title`.

Thanks a lot!

Cheers,
Imre

**Comment by gubler** [comment]
I've been thinking about this, and I dislike remove the callout Type from the header for a few reasons.

The icon is a visual delimiter, but it doesn't _actually_ convey the type to someone - it might after they have seen the same icon next to the type in the header, but without that type information the icon is just an icon.

Color can not be relied on for both accessibility (if someone is unable to see color or is using a device that does not display that information) and because the some colors are used by multiple types.

I think I see a way of adding a configuration option to show/hide the type information in the header, and  I will look into that when I have a chance, but that may not be for a week or so.

**Comment by nagim** [comment]
I didn't mean removing every information from the title.
But now the title info is duplicated (**Note: Note**, etc.) or what if someone doesn't want to use **Warning** as a title, but would like use **Important** instead (right now it's only possible like this: **Warning: Important**, which is kind of superfluous).

Configuration option sounds good.
Thanks!

**Comment by nagim** [comment]
Hi,

Thanks a lot for making an update!
However, I checked by setting the `showTypeInHeader` attribute to false and it still shows the type.

Cheers,
Imre

**Comment by gubler** [comment]
OK - looks like I didn't create a release on GitHub for v0.0.8. That has (finally) been done.

Make sure your `package.json` is pulling the new version and it should work.

Sorry about that.

**Comment by nagim** [comment]
Thanks for the reply!

It wasn't the problem, it was published on `npm` with the correct version (0.0.8).
So still it doesn't work for me.

My `book.json`:

``` json
{
    "gitbook": "2.x.x",
    "plugins": [
        "addcssjs",
        "comment",
        "include",
        "-sharing",
        "anchor-navigation",
        "ungrey",
        "toggle-chapters",
        "book-summary-scroll-position-saver",
        "splitter",
        "versions",
        "richquotes",
        "copy-code-button",
        "codesnippet",
        "sections",
        "callouts",
        "puml",
        "sectionx",
        "hints"
    ],
    "pluginsConfig": {
        "versions": {
            "type": "branches"
        },
        "richquotes": {
            "danger": {
                "alert": "danger",
                "picto": "fa-exclamation-triangle"
            },
            "warning": {
                "alert": "warning",
                "picto": "fa-exclamation-circle"
            }
        },
        "callouts": {
                "showTypeInHeader": false
         },
        "addcssjs": {
            "js": ["styles/test.js"]
        }
    }
}
```

Example syntax from the source file:

``` asciidoc
> ==== Info::Note
> 
> This is a note
```

Thanks,
Imre

**Comment by nagim** [comment]
Hi,

I checked my topics more carefully and here is the problem: if I use the plugin in a markdown file, the config options works fine.
It only breaks in asciidoc files.

Thanks,
Imre

**Comment by nagim** [comment]
Hi,

Seems that [this part](https://github.com/gubler/gitbook-plugin-callouts/blob/master/index.js#L141) runs only in case of markdown code (it's missing from the asciidoc specific block), so it should be an easier fix, since the function is working, it's just not called in case of asciidoc code.

Could you please add this to asciidoc part as well?

Thanks,
Imre

**Comment by gubler** [comment]
Yeah - you're right. I've added it in - it worked in my test with an asciidoc example, but please check it and make sure.

**Comment by nagim** [comment]
Thanks, could you please publish on npm, too?

**Comment by nagim** [comment]
Awesome, tested and works fine!

Thanks a lot! :beers:

**Comment by gubler** [comment]
Thanks for finding my mistake. I am abashed that I missed that :)
