### ISSUE TITLE
Apply styles in PDF

### ISSUE THREAD

**Issue by bronestly** [gubler/gitbook-plugin-callouts#3]
Is there a way to get the styles in PDF output?

**Comment by gubler** [comment]
I haven't tried doing exports. Try copying the styles in the [css file](https://github.com/gubler/gitbook-plugin-callouts/blob/master/book/plugin.css) to your ebook or pdf stylesheets ([see the gitbook documentation here](https://help.gitbook.com/styling/book.html)) and see if that will get them to work in your PDF.

**Comment by gubler** [comment]
Closing this as I can't see a way to push plugin styles to PDF from the plugin. Please let me know if the workaround I suggested above works or not.
