### ISSUE TITLE
seems does not work in the gitbook online editor?

### ISSUE THREAD

**Issue by datafibers** [gubler/gitbook-plugin-callouts#7]
does it work in the gitbook online editor?

**Comment by gubler** [comment]
Just created an account and checked and though the editor doesn't render it properly, once you publish the document and view it online it looks correct.

Here is an example: https://dev88.gitbooks.io/callout-testing/content/

To be honest with you, I do not have the time to try and get this plugin to work with Gitbook's online editor (if it even can). You are welcome to mess with the code and send pull requests if you get it to render in the online editor.
